//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Detail obj.
    /// </summary>
    // *** Start programmer edit section *** (DetailObj CustomAttributes)

    // *** End programmer edit section *** (DetailObj CustomAttributes)
    [AutoAltered()]
    [Caption("Detail obj")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "DetailName as \'Detail name\'",
            "DetailField as \'Detail field\'",
            "DetailMaster as \'Detail master\'",
            "DetailMaster.Name as \'Name\'"}, Hidden=new string[] {
            "DetailMaster.Name"})]
    [MasterViewDefineAttribute("AuditView", "DetailMaster", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("DetailObjD", new string[] {
            "DetailName",
            "DetailField",
            "MainObj",
            "DetailMaster"}, Hidden=new string[] {
            "MainObj"})]
    [MasterViewDefineAttribute("DetailObjD", "DetailMaster", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("DetailObjE", new string[] {
            "DetailName as \'Detail name\'",
            "DetailField as \'Detail field\'"})]
    [View("DetailObjL", new string[] {
            "DetailName",
            "DetailField"})]
    public class DetailObj : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fDetailName;
        
        private int fDetailField;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private SimpleTestAuditProject.DetailMaster fDetailMaster;
        
        private SimpleTestAuditProject.MainObj fMainObj;
        
        // *** Start programmer edit section *** (DetailObj CustomMembers)

        // *** End programmer edit section *** (DetailObj CustomMembers)

        
        /// <summary>
        /// DetailName.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.DetailName CustomAttributes)

        // *** End programmer edit section *** (DetailObj.DetailName CustomAttributes)
        [StrLen(255)]
        public virtual string DetailName
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.DetailName Get start)

                // *** End programmer edit section *** (DetailObj.DetailName Get start)
                string result = this.fDetailName;
                // *** Start programmer edit section *** (DetailObj.DetailName Get end)

                // *** End programmer edit section *** (DetailObj.DetailName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.DetailName Set start)

                // *** End programmer edit section *** (DetailObj.DetailName Set start)
                this.fDetailName = value;
                // *** Start programmer edit section *** (DetailObj.DetailName Set end)

                // *** End programmer edit section *** (DetailObj.DetailName Set end)
            }
        }
        
        /// <summary>
        /// DetailField.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.DetailField CustomAttributes)

        // *** End programmer edit section *** (DetailObj.DetailField CustomAttributes)
        public virtual int DetailField
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.DetailField Get start)

                // *** End programmer edit section *** (DetailObj.DetailField Get start)
                int result = this.fDetailField;
                // *** Start programmer edit section *** (DetailObj.DetailField Get end)

                // *** End programmer edit section *** (DetailObj.DetailField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.DetailField Set start)

                // *** End programmer edit section *** (DetailObj.DetailField Set start)
                this.fDetailField = value;
                // *** Start programmer edit section *** (DetailObj.DetailField Set end)

                // *** End programmer edit section *** (DetailObj.DetailField Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.CreateTime CustomAttributes)

        // *** End programmer edit section *** (DetailObj.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.CreateTime Get start)

                // *** End programmer edit section *** (DetailObj.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (DetailObj.CreateTime Get end)

                // *** End programmer edit section *** (DetailObj.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.CreateTime Set start)

                // *** End programmer edit section *** (DetailObj.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (DetailObj.CreateTime Set end)

                // *** End programmer edit section *** (DetailObj.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.Creator CustomAttributes)

        // *** End programmer edit section *** (DetailObj.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.Creator Get start)

                // *** End programmer edit section *** (DetailObj.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (DetailObj.Creator Get end)

                // *** End programmer edit section *** (DetailObj.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.Creator Set start)

                // *** End programmer edit section *** (DetailObj.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (DetailObj.Creator Set end)

                // *** End programmer edit section *** (DetailObj.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.EditTime CustomAttributes)

        // *** End programmer edit section *** (DetailObj.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.EditTime Get start)

                // *** End programmer edit section *** (DetailObj.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (DetailObj.EditTime Get end)

                // *** End programmer edit section *** (DetailObj.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.EditTime Set start)

                // *** End programmer edit section *** (DetailObj.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (DetailObj.EditTime Set end)

                // *** End programmer edit section *** (DetailObj.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.Editor CustomAttributes)

        // *** End programmer edit section *** (DetailObj.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.Editor Get start)

                // *** End programmer edit section *** (DetailObj.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (DetailObj.Editor Get end)

                // *** End programmer edit section *** (DetailObj.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.Editor Set start)

                // *** End programmer edit section *** (DetailObj.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (DetailObj.Editor Set end)

                // *** End programmer edit section *** (DetailObj.Editor Set end)
            }
        }
        
        /// <summary>
        /// Detail obj.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.DetailMaster CustomAttributes)

        // *** End programmer edit section *** (DetailObj.DetailMaster CustomAttributes)
        [PropertyStorage(new string[] {
                "DetailMaster"})]
        public virtual SimpleTestAuditProject.DetailMaster DetailMaster
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.DetailMaster Get start)

                // *** End programmer edit section *** (DetailObj.DetailMaster Get start)
                SimpleTestAuditProject.DetailMaster result = this.fDetailMaster;
                // *** Start programmer edit section *** (DetailObj.DetailMaster Get end)

                // *** End programmer edit section *** (DetailObj.DetailMaster Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.DetailMaster Set start)

                // *** End programmer edit section *** (DetailObj.DetailMaster Set start)
                this.fDetailMaster = value;
                // *** Start programmer edit section *** (DetailObj.DetailMaster Set end)

                // *** End programmer edit section *** (DetailObj.DetailMaster Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку SimpleTestAuditProject.MainObj.
        /// </summary>
        // *** Start programmer edit section *** (DetailObj.MainObj CustomAttributes)

        // *** End programmer edit section *** (DetailObj.MainObj CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "MainObj"})]
        public virtual SimpleTestAuditProject.MainObj MainObj
        {
            get
            {
                // *** Start programmer edit section *** (DetailObj.MainObj Get start)

                // *** End programmer edit section *** (DetailObj.MainObj Get start)
                SimpleTestAuditProject.MainObj result = this.fMainObj;
                // *** Start programmer edit section *** (DetailObj.MainObj Get end)

                // *** End programmer edit section *** (DetailObj.MainObj Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailObj.MainObj Set start)

                // *** End programmer edit section *** (DetailObj.MainObj Set start)
                this.fMainObj = value;
                // *** Start programmer edit section *** (DetailObj.MainObj Set end)

                // *** End programmer edit section *** (DetailObj.MainObj Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(SimpleTestAuditProject.DetailObj));
                }
            }
            
            /// <summary>
            /// "DetailObjD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DetailObjD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DetailObjD", typeof(SimpleTestAuditProject.DetailObj));
                }
            }
            
            /// <summary>
            /// "DetailObjE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DetailObjE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DetailObjE", typeof(SimpleTestAuditProject.DetailObj));
                }
            }
            
            /// <summary>
            /// "DetailObjL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DetailObjL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DetailObjL", typeof(SimpleTestAuditProject.DetailObj));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of DetailObj.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDetailObj CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDetailObj CustomAttributes)
    public class DetailArrayOfDetailObj : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (SimpleTestAuditProject.DetailArrayOfDetailObj members)

        // *** End programmer edit section *** (SimpleTestAuditProject.DetailArrayOfDetailObj members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DetailObj by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DetailObj.
        /// </summary>
        public DetailArrayOfDetailObj(SimpleTestAuditProject.MainObj fMainObj) : 
                base(typeof(DetailObj), ((ICSSoft.STORMNET.DataObject)(fMainObj)))
        {
        }
        
        public SimpleTestAuditProject.DetailObj this[int index]
        {
            get
            {
                return ((SimpleTestAuditProject.DetailObj)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(SimpleTestAuditProject.DetailObj dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
