//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Master obj.
    /// </summary>
    // *** Start programmer edit section *** (MasterObj CustomAttributes)

    // *** End programmer edit section *** (MasterObj CustomAttributes)
    [AutoAltered()]
    [Caption("Master obj")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "MasterName as \'Master name\'",
            "MasterField as \'Master field\'"})]
    [AssociatedDetailViewAttribute("AuditView", "MasterDetail", "AuditView", true, "", "Master detail", true, new string[] {
            ""})]
    [View("MasterObjE", new string[] {
            "MasterName",
            "MasterField"})]
    [AssociatedDetailViewAttribute("MasterObjE", "MasterDetail", "MasterDetailD", true, "", "", true, new string[] {
            ""})]
    [View("MasterObjL", new string[] {
            "MasterName",
            "MasterField"})]
    public class MasterObj : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fMasterName;
        
        private int fMasterField;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private SimpleTestAuditProject.DetailArrayOfMasterDetail fMasterDetail;
        
        // *** Start programmer edit section *** (MasterObj CustomMembers)

        // *** End programmer edit section *** (MasterObj CustomMembers)

        
        /// <summary>
        /// MasterName.
        /// </summary>
        // *** Start programmer edit section *** (MasterObj.MasterName CustomAttributes)

        // *** End programmer edit section *** (MasterObj.MasterName CustomAttributes)
        [StrLen(255)]
        public virtual string MasterName
        {
            get
            {
                // *** Start programmer edit section *** (MasterObj.MasterName Get start)

                // *** End programmer edit section *** (MasterObj.MasterName Get start)
                string result = this.fMasterName;
                // *** Start programmer edit section *** (MasterObj.MasterName Get end)

                // *** End programmer edit section *** (MasterObj.MasterName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterObj.MasterName Set start)

                // *** End programmer edit section *** (MasterObj.MasterName Set start)
                this.fMasterName = value;
                // *** Start programmer edit section *** (MasterObj.MasterName Set end)

                // *** End programmer edit section *** (MasterObj.MasterName Set end)
            }
        }
        
        /// <summary>
        /// MasterField.
        /// </summary>
        // *** Start programmer edit section *** (MasterObj.MasterField CustomAttributes)

        // *** End programmer edit section *** (MasterObj.MasterField CustomAttributes)
        public virtual int MasterField
        {
            get
            {
                // *** Start programmer edit section *** (MasterObj.MasterField Get start)

                // *** End programmer edit section *** (MasterObj.MasterField Get start)
                int result = this.fMasterField;
                // *** Start programmer edit section *** (MasterObj.MasterField Get end)

                // *** End programmer edit section *** (MasterObj.MasterField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterObj.MasterField Set start)

                // *** End programmer edit section *** (MasterObj.MasterField Set start)
                this.fMasterField = value;
                // *** Start programmer edit section *** (MasterObj.MasterField Set end)

                // *** End programmer edit section *** (MasterObj.MasterField Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterObj.CreateTime CustomAttributes)

        // *** End programmer edit section *** (MasterObj.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (MasterObj.CreateTime Get start)

                // *** End programmer edit section *** (MasterObj.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (MasterObj.CreateTime Get end)

                // *** End programmer edit section *** (MasterObj.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterObj.CreateTime Set start)

                // *** End programmer edit section *** (MasterObj.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (MasterObj.CreateTime Set end)

                // *** End programmer edit section *** (MasterObj.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterObj.Creator CustomAttributes)

        // *** End programmer edit section *** (MasterObj.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (MasterObj.Creator Get start)

                // *** End programmer edit section *** (MasterObj.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (MasterObj.Creator Get end)

                // *** End programmer edit section *** (MasterObj.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterObj.Creator Set start)

                // *** End programmer edit section *** (MasterObj.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (MasterObj.Creator Set end)

                // *** End programmer edit section *** (MasterObj.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterObj.EditTime CustomAttributes)

        // *** End programmer edit section *** (MasterObj.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (MasterObj.EditTime Get start)

                // *** End programmer edit section *** (MasterObj.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (MasterObj.EditTime Get end)

                // *** End programmer edit section *** (MasterObj.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterObj.EditTime Set start)

                // *** End programmer edit section *** (MasterObj.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (MasterObj.EditTime Set end)

                // *** End programmer edit section *** (MasterObj.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterObj.Editor CustomAttributes)

        // *** End programmer edit section *** (MasterObj.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (MasterObj.Editor Get start)

                // *** End programmer edit section *** (MasterObj.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (MasterObj.Editor Get end)

                // *** End programmer edit section *** (MasterObj.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterObj.Editor Set start)

                // *** End programmer edit section *** (MasterObj.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (MasterObj.Editor Set end)

                // *** End programmer edit section *** (MasterObj.Editor Set end)
            }
        }
        
        /// <summary>
        /// Master obj.
        /// </summary>
        // *** Start programmer edit section *** (MasterObj.MasterDetail CustomAttributes)

        // *** End programmer edit section *** (MasterObj.MasterDetail CustomAttributes)
        public virtual SimpleTestAuditProject.DetailArrayOfMasterDetail MasterDetail
        {
            get
            {
                // *** Start programmer edit section *** (MasterObj.MasterDetail Get start)

                // *** End programmer edit section *** (MasterObj.MasterDetail Get start)
                if ((this.fMasterDetail == null))
                {
                    this.fMasterDetail = new SimpleTestAuditProject.DetailArrayOfMasterDetail(this);
                }
                SimpleTestAuditProject.DetailArrayOfMasterDetail result = this.fMasterDetail;
                // *** Start programmer edit section *** (MasterObj.MasterDetail Get end)

                // *** End programmer edit section *** (MasterObj.MasterDetail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterObj.MasterDetail Set start)

                // *** End programmer edit section *** (MasterObj.MasterDetail Set start)
                this.fMasterDetail = value;
                // *** Start programmer edit section *** (MasterObj.MasterDetail Set end)

                // *** End programmer edit section *** (MasterObj.MasterDetail Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(SimpleTestAuditProject.MasterObj));
                }
            }
            
            /// <summary>
            /// "MasterObjE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterObjE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterObjE", typeof(SimpleTestAuditProject.MasterObj));
                }
            }
            
            /// <summary>
            /// "MasterObjL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterObjL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterObjL", typeof(SimpleTestAuditProject.MasterObj));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
