import SimpleTestAuditProjectDetailMasterEController from '../simple-test-audit-project-detail-master-e';

var SimpleTestAuditProjectDetailMasterENewController = SimpleTestAuditProjectDetailMasterEController;
export default SimpleTestAuditProjectDetailMasterENewController;
