//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DetailMaster.
    /// </summary>
    // *** Start programmer edit section *** (DetailMaster CustomAttributes)

    // *** End programmer edit section *** (DetailMaster CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Name as \'Name\'",
            "Field1 as \'Field1\'",
            "Field2 as \'Field2\'"})]
    [View("DetailMasterE", new string[] {
            "Name",
            "Field1",
            "Field2"})]
    [View("DetailMasterL", new string[] {
            "Name",
            "Field1",
            "Field2"})]
    public class DetailMaster : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fName;
        
        private int fField1;
        
        private string fField2;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (DetailMaster CustomMembers)

        // *** End programmer edit section *** (DetailMaster CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (DetailMaster.Name CustomAttributes)

        // *** End programmer edit section *** (DetailMaster.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (DetailMaster.Name Get start)

                // *** End programmer edit section *** (DetailMaster.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (DetailMaster.Name Get end)

                // *** End programmer edit section *** (DetailMaster.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailMaster.Name Set start)

                // *** End programmer edit section *** (DetailMaster.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (DetailMaster.Name Set end)

                // *** End programmer edit section *** (DetailMaster.Name Set end)
            }
        }
        
        /// <summary>
        /// Field1.
        /// </summary>
        // *** Start programmer edit section *** (DetailMaster.Field1 CustomAttributes)

        // *** End programmer edit section *** (DetailMaster.Field1 CustomAttributes)
        public virtual int Field1
        {
            get
            {
                // *** Start programmer edit section *** (DetailMaster.Field1 Get start)

                // *** End programmer edit section *** (DetailMaster.Field1 Get start)
                int result = this.fField1;
                // *** Start programmer edit section *** (DetailMaster.Field1 Get end)

                // *** End programmer edit section *** (DetailMaster.Field1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailMaster.Field1 Set start)

                // *** End programmer edit section *** (DetailMaster.Field1 Set start)
                this.fField1 = value;
                // *** Start programmer edit section *** (DetailMaster.Field1 Set end)

                // *** End programmer edit section *** (DetailMaster.Field1 Set end)
            }
        }
        
        /// <summary>
        /// Field2.
        /// </summary>
        // *** Start programmer edit section *** (DetailMaster.Field2 CustomAttributes)

        // *** End programmer edit section *** (DetailMaster.Field2 CustomAttributes)
        [StrLen(255)]
        public virtual string Field2
        {
            get
            {
                // *** Start programmer edit section *** (DetailMaster.Field2 Get start)

                // *** End programmer edit section *** (DetailMaster.Field2 Get start)
                string result = this.fField2;
                // *** Start programmer edit section *** (DetailMaster.Field2 Get end)

                // *** End programmer edit section *** (DetailMaster.Field2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailMaster.Field2 Set start)

                // *** End programmer edit section *** (DetailMaster.Field2 Set start)
                this.fField2 = value;
                // *** Start programmer edit section *** (DetailMaster.Field2 Set end)

                // *** End programmer edit section *** (DetailMaster.Field2 Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailMaster.CreateTime CustomAttributes)

        // *** End programmer edit section *** (DetailMaster.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (DetailMaster.CreateTime Get start)

                // *** End programmer edit section *** (DetailMaster.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (DetailMaster.CreateTime Get end)

                // *** End programmer edit section *** (DetailMaster.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailMaster.CreateTime Set start)

                // *** End programmer edit section *** (DetailMaster.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (DetailMaster.CreateTime Set end)

                // *** End programmer edit section *** (DetailMaster.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailMaster.Creator CustomAttributes)

        // *** End programmer edit section *** (DetailMaster.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (DetailMaster.Creator Get start)

                // *** End programmer edit section *** (DetailMaster.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (DetailMaster.Creator Get end)

                // *** End programmer edit section *** (DetailMaster.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailMaster.Creator Set start)

                // *** End programmer edit section *** (DetailMaster.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (DetailMaster.Creator Set end)

                // *** End programmer edit section *** (DetailMaster.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailMaster.EditTime CustomAttributes)

        // *** End programmer edit section *** (DetailMaster.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (DetailMaster.EditTime Get start)

                // *** End programmer edit section *** (DetailMaster.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (DetailMaster.EditTime Get end)

                // *** End programmer edit section *** (DetailMaster.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailMaster.EditTime Set start)

                // *** End programmer edit section *** (DetailMaster.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (DetailMaster.EditTime Set end)

                // *** End programmer edit section *** (DetailMaster.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (DetailMaster.Editor CustomAttributes)

        // *** End programmer edit section *** (DetailMaster.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (DetailMaster.Editor Get start)

                // *** End programmer edit section *** (DetailMaster.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (DetailMaster.Editor Get end)

                // *** End programmer edit section *** (DetailMaster.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailMaster.Editor Set start)

                // *** End programmer edit section *** (DetailMaster.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (DetailMaster.Editor Set end)

                // *** End programmer edit section *** (DetailMaster.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(SimpleTestAuditProject.DetailMaster));
                }
            }
            
            /// <summary>
            /// "DetailMasterE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DetailMasterE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DetailMasterE", typeof(SimpleTestAuditProject.DetailMaster));
                }
            }
            
            /// <summary>
            /// "DetailMasterL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DetailMasterL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DetailMasterL", typeof(SimpleTestAuditProject.DetailMaster));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
