//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTestAuditProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MasterDetail.
    /// </summary>
    // *** Start programmer edit section *** (MasterDetail CustomAttributes)

    // *** End programmer edit section *** (MasterDetail CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Field as \'Field\'"})]
    [View("MasterDetailD", new string[] {
            "Field",
            "MasterObj"}, Hidden=new string[] {
            "MasterObj"})]
    public class MasterDetail : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fField;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private SimpleTestAuditProject.MasterObj fMasterObj;
        
        // *** Start programmer edit section *** (MasterDetail CustomMembers)

        // *** End programmer edit section *** (MasterDetail CustomMembers)

        
        /// <summary>
        /// Field.
        /// </summary>
        // *** Start programmer edit section *** (MasterDetail.Field CustomAttributes)

        // *** End programmer edit section *** (MasterDetail.Field CustomAttributes)
        [StrLen(255)]
        public virtual string Field
        {
            get
            {
                // *** Start programmer edit section *** (MasterDetail.Field Get start)

                // *** End programmer edit section *** (MasterDetail.Field Get start)
                string result = this.fField;
                // *** Start programmer edit section *** (MasterDetail.Field Get end)

                // *** End programmer edit section *** (MasterDetail.Field Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterDetail.Field Set start)

                // *** End programmer edit section *** (MasterDetail.Field Set start)
                this.fField = value;
                // *** Start programmer edit section *** (MasterDetail.Field Set end)

                // *** End programmer edit section *** (MasterDetail.Field Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterDetail.CreateTime CustomAttributes)

        // *** End programmer edit section *** (MasterDetail.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (MasterDetail.CreateTime Get start)

                // *** End programmer edit section *** (MasterDetail.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (MasterDetail.CreateTime Get end)

                // *** End programmer edit section *** (MasterDetail.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterDetail.CreateTime Set start)

                // *** End programmer edit section *** (MasterDetail.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (MasterDetail.CreateTime Set end)

                // *** End programmer edit section *** (MasterDetail.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterDetail.Creator CustomAttributes)

        // *** End programmer edit section *** (MasterDetail.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (MasterDetail.Creator Get start)

                // *** End programmer edit section *** (MasterDetail.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (MasterDetail.Creator Get end)

                // *** End programmer edit section *** (MasterDetail.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterDetail.Creator Set start)

                // *** End programmer edit section *** (MasterDetail.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (MasterDetail.Creator Set end)

                // *** End programmer edit section *** (MasterDetail.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterDetail.EditTime CustomAttributes)

        // *** End programmer edit section *** (MasterDetail.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (MasterDetail.EditTime Get start)

                // *** End programmer edit section *** (MasterDetail.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (MasterDetail.EditTime Get end)

                // *** End programmer edit section *** (MasterDetail.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterDetail.EditTime Set start)

                // *** End programmer edit section *** (MasterDetail.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (MasterDetail.EditTime Set end)

                // *** End programmer edit section *** (MasterDetail.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (MasterDetail.Editor CustomAttributes)

        // *** End programmer edit section *** (MasterDetail.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (MasterDetail.Editor Get start)

                // *** End programmer edit section *** (MasterDetail.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (MasterDetail.Editor Get end)

                // *** End programmer edit section *** (MasterDetail.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterDetail.Editor Set start)

                // *** End programmer edit section *** (MasterDetail.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (MasterDetail.Editor Set end)

                // *** End programmer edit section *** (MasterDetail.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку SimpleTestAuditProject.MasterObj.
        /// </summary>
        // *** Start programmer edit section *** (MasterDetail.MasterObj CustomAttributes)

        // *** End programmer edit section *** (MasterDetail.MasterObj CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "MasterObj"})]
        public virtual SimpleTestAuditProject.MasterObj MasterObj
        {
            get
            {
                // *** Start programmer edit section *** (MasterDetail.MasterObj Get start)

                // *** End programmer edit section *** (MasterDetail.MasterObj Get start)
                SimpleTestAuditProject.MasterObj result = this.fMasterObj;
                // *** Start programmer edit section *** (MasterDetail.MasterObj Get end)

                // *** End programmer edit section *** (MasterDetail.MasterObj Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterDetail.MasterObj Set start)

                // *** End programmer edit section *** (MasterDetail.MasterObj Set start)
                this.fMasterObj = value;
                // *** Start programmer edit section *** (MasterDetail.MasterObj Set end)

                // *** End programmer edit section *** (MasterDetail.MasterObj Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(SimpleTestAuditProject.MasterDetail));
                }
            }
            
            /// <summary>
            /// "MasterDetailD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MasterDetailD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MasterDetailD", typeof(SimpleTestAuditProject.MasterDetail));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of MasterDetail.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfMasterDetail CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfMasterDetail CustomAttributes)
    public class DetailArrayOfMasterDetail : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (SimpleTestAuditProject.DetailArrayOfMasterDetail members)

        // *** End programmer edit section *** (SimpleTestAuditProject.DetailArrayOfMasterDetail members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type MasterDetail by index.
        /// </summary>
        /// <summary>
        /// Adds object with type MasterDetail.
        /// </summary>
        public DetailArrayOfMasterDetail(SimpleTestAuditProject.MasterObj fMasterObj) : 
                base(typeof(MasterDetail), ((ICSSoft.STORMNET.DataObject)(fMasterObj)))
        {
        }
        
        public SimpleTestAuditProject.MasterDetail this[int index]
        {
            get
            {
                return ((SimpleTestAuditProject.MasterDetail)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(SimpleTestAuditProject.MasterDetail dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
